package diff

import (
	"testing"

	"github.com/aiven/aiven-go-client/tools/exp/types"
	"github.com/google/go-cmp/cmp"
)

// TestDiff tests the diff function.
func TestDiff(t *testing.T) {
	type args struct {
		g map[string]types.UserConfigSchema
		r map[string]types.UserConfigSchema
	}

	tests := []struct {
		name    string
		args    args
		want    map[string]types.UserConfigSchema
		wantErr error
	}{
		{
			name: "no read schema",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum:                            nil,
						Minimum:                         0,
						Maximum:                         0,
						MinLength:                       0,
						MaxLength:                       0,
						MaxItems:                        0,
						CreateOnly:                      false,
						Pattern:                         "",
						Example:                         nil,
						UserError:                       "",
					},
				},
				r: nil,
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties:                      nil,
					Items:                           nil,
					OneOf:                           nil,
					Enum:                            nil,
					Minimum:                         0,
					Maximum:                         0,
					MinLength:                       0,
					MaxLength:                       0,
					MaxItems:                        0,
					CreateOnly:                      false,
					Pattern:                         "",
					Example:                         nil,
					UserError:                       "",
				},
			},
			wantErr: nil,
		},
		{
			name: "equal schemas",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum:                            nil,
						Minimum:                         0,
						Maximum:                         0,
						MinLength:                       0,
						MaxLength:                       0,
						MaxItems:                        0,
						CreateOnly:                      false,
						Pattern:                         "",
						Example:                         nil,
						UserError:                       "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum:                            nil,
						Minimum:                         0,
						Maximum:                         0,
						MinLength:                       0,
						MaxLength:                       0,
						MaxItems:                        0,
						CreateOnly:                      false,
						Pattern:                         "",
						Example:                         nil,
						UserError:                       "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties:                      nil,
					Items:                           nil,
					OneOf:                           nil,
					Enum:                            nil,
					Minimum:                         0,
					Maximum:                         0,
					MinLength:                       0,
					MaxLength:                       0,
					MaxItems:                        0,
					CreateOnly:                      false,
					Pattern:                         "",
					Example:                         nil,
					UserError:                       "",
				},
			},
			wantErr: nil,
		},
		{
			name: "different schemas",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "bar",
						Description:                     "bar",
						Type:                            "bar",
						Default:                         "bar",
						Properties: map[string]types.UserConfigSchema{
							"baz": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         0,
								Maximum:                         0,
								MinLength:                       0,
								MaxLength:                       0,
								MaxItems:                        0,
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items: &types.UserConfigSchema{
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties: map[string]types.UserConfigSchema{
								"qux": {
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items: &types.UserConfigSchema{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf: []types.UserConfigSchema{
											{
												UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
												Title:                           "quux",
												Description:                     "",
												Type:                            nil,
												Default:                         nil,
												Properties:                      nil,
												Items:                           nil,
												OneOf:                           nil,
												Enum:                            nil,
												Minimum:                         0,
												Maximum:                         0,
												MinLength:                       0,
												MaxLength:                       0,
												MaxItems:                        0,
												CreateOnly:                      false,
												Pattern:                         "",
												Example:                         nil,
												UserError:                       "",
											},
										},
										Enum:       nil,
										Minimum:    0,
										Maximum:    0,
										MinLength:  0,
										MaxLength:  0,
										MaxItems:   0,
										CreateOnly: false,
										Pattern:    "",
										Example:    nil,
										UserError:  "",
									},
									OneOf:      nil,
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
							},
							Items:      nil,
							OneOf:      nil,
							Enum:       nil,
							Minimum:    0,
							Maximum:    0,
							MinLength:  0,
							MaxLength:  0,
							MaxItems:   0,
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
						OneOf: nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Value:                           "corge",
							},
						},
						Minimum:    1,
						Maximum:    1,
						MinLength:  1,
						MaxLength:  1,
						MaxItems:   1,
						CreateOnly: false,
						Pattern:    "bar",
						Example:    "bar",
						UserError:  "bar",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum:                            nil,
						Minimum:                         0,
						Maximum:                         0,
						MinLength:                       0,
						MaxLength:                       0,
						MaxItems:                        0,
						CreateOnly:                      false,
						Pattern:                         "",
						Example:                         nil,
						UserError:                       "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "bar",
					Description:                     "bar",
					Type:                            "bar",
					Default:                         "bar",
					Properties: map[string]types.UserConfigSchema{
						"baz": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items:                           nil,
							OneOf:                           nil,
							Enum:                            nil,
							Minimum:                         0,
							Maximum:                         0,
							MinLength:                       0,
							MaxLength:                       0,
							MaxItems:                        0,
							CreateOnly:                      false,
							Pattern:                         "",
							Example:                         nil,
							UserError:                       "",
						},
					},
					Items: &types.UserConfigSchema{
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"qux": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "quux",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
					OneOf: nil,
					Enum: []types.UserConfigSchemaEnumValue{
						{
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Value:                           "corge",
						},
					},
					Minimum:    1,
					Maximum:    1,
					MinLength:  1,
					MaxLength:  1,
					MaxItems:   1,
					CreateOnly: false,
					Pattern:    "bar",
					Example:    "bar",
					UserError:  "bar",
				},
			},
			wantErr: nil,
		},
		{
			name: "gen new property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         0,
								Maximum:                         0,
								MinLength:                       0,
								MaxLength:                       0,
								MaxItems:                        0,
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
							"baz": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         0,
								Maximum:                         0,
								MinLength:                       0,
								MaxLength:                       0,
								MaxItems:                        0,
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         0,
								Maximum:                         0,
								MinLength:                       0,
								MaxLength:                       0,
								MaxItems:                        0,
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items:                           nil,
							OneOf:                           nil,
							Enum:                            nil,
							Minimum:                         0,
							Maximum:                         0,
							MinLength:                       0,
							MaxLength:                       0,
							MaxItems:                        0,
							CreateOnly:                      false,
							Pattern:                         "",
							Example:                         nil,
							UserError:                       "",
						},
						"baz": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items:                           nil,
							OneOf:                           nil,
							Enum:                            nil,
							Minimum:                         0,
							Maximum:                         0,
							MinLength:                       0,
							MaxLength:                       0,
							MaxItems:                        0,
							CreateOnly:                      false,
							Pattern:                         "",
							Example:                         nil,
							UserError:                       "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    0,
					Maximum:    0,
					MinLength:  0,
					MaxLength:  0,
					MaxItems:   0,
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
			wantErr: nil,
		},
		{
			name: "read new property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         0,
								Maximum:                         0,
								MinLength:                       0,
								MaxLength:                       0,
								MaxItems:                        0,
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         0,
								Maximum:                         0,
								MinLength:                       0,
								MaxLength:                       0,
								MaxItems:                        0,
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
							"baz": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf:                           nil,
								Enum:                            nil,
								Minimum:                         0,
								Maximum:                         0,
								MinLength:                       0,
								MaxLength:                       0,
								MaxItems:                        0,
								CreateOnly:                      false,
								Pattern:                         "",
								Example:                         nil,
								UserError:                       "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items:                           nil,
							OneOf:                           nil,
							Enum:                            nil,
							Minimum:                         0,
							Maximum:                         0,
							MinLength:                       0,
							MaxLength:                       0,
							MaxItems:                        0,
							CreateOnly:                      false,
							Pattern:                         "",
							Example:                         nil,
							UserError:                       "",
						},
						"baz": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{
								IsDeprecated:      true,
								DeprecationNotice: "This property is deprecated.",
							},
							Title:       "",
							Description: "",
							Type:        nil,
							Default:     nil,
							Properties:  nil,
							Items:       nil,
							OneOf:       nil,
							Enum:        nil,
							Minimum:     0,
							Maximum:     0,
							MinLength:   0,
							MaxLength:   0,
							MaxItems:    0,
							CreateOnly:  false,
							Pattern:     "",
							Example:     nil,
							UserError:   "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    0,
					Maximum:    0,
					MinLength:  0,
					MaxLength:  0,
					MaxItems:   0,
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
			wantErr: nil,
		},
		{
			name: "gen new item property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties: map[string]types.UserConfigSchema{
										"bar": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
										"baz": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Items:      nil,
									OneOf:      nil,
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties: map[string]types.UserConfigSchema{
										"bar": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Items:      nil,
									OneOf:      nil,
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items: &types.UserConfigSchema{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties: map[string]types.UserConfigSchema{
									"bar": {
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         0,
										Maximum:                         0,
										MinLength:                       0,
										MaxLength:                       0,
										MaxItems:                        0,
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
									"baz": {
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         0,
										Maximum:                         0,
										MinLength:                       0,
										MaxLength:                       0,
										MaxItems:                        0,
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
								},
								Items:      nil,
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
							OneOf:      nil,
							Enum:       nil,
							Minimum:    0,
							Maximum:    0,
							MinLength:  0,
							MaxLength:  0,
							MaxItems:   0,
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    0,
					Maximum:    0,
					MinLength:  0,
					MaxLength:  0,
					MaxItems:   0,
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
			wantErr: nil,
		},
		{
			name: "read new item property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties: map[string]types.UserConfigSchema{
										"bar": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Items:      nil,
									OneOf:      nil,
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties: map[string]types.UserConfigSchema{
										"bar": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
										"baz": {
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Items:      nil,
									OneOf:      nil,
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items: &types.UserConfigSchema{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties: map[string]types.UserConfigSchema{
									"bar": {
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         0,
										Maximum:                         0,
										MinLength:                       0,
										MaxLength:                       0,
										MaxItems:                        0,
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
									"baz": {
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{
											IsDeprecated:      true,
											DeprecationNotice: "This property is deprecated.",
										},
										Title:       "",
										Description: "",
										Type:        nil,
										Default:     nil,
										Properties:  nil,
										Items:       nil,
										OneOf:       nil,
										Enum:        nil,
										Minimum:     0,
										Maximum:     0,
										MinLength:   0,
										MaxLength:   0,
										MaxItems:    0,
										CreateOnly:  false,
										Pattern:     "",
										Example:     nil,
										UserError:   "",
									},
								},
								Items:      nil,
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
							OneOf:      nil,
							Enum:       nil,
							Minimum:    0,
							Maximum:    0,
							MinLength:  0,
							MaxLength:  0,
							MaxItems:   0,
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    0,
					Maximum:    0,
					MinLength:  0,
					MaxLength:  0,
					MaxItems:   0,
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
			wantErr: nil,
		},
		{
			name: "gen new item one of property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "qux",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "quux",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "qux",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items: &types.UserConfigSchema{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf: []types.UserConfigSchema{
									{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "qux",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         0,
										Maximum:                         0,
										MinLength:                       0,
										MaxLength:                       0,
										MaxItems:                        0,
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
									{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "quux",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         0,
										Maximum:                         0,
										MinLength:                       0,
										MaxLength:                       0,
										MaxItems:                        0,
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
								},
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
							OneOf:      nil,
							Enum:       nil,
							Minimum:    0,
							Maximum:    0,
							MinLength:  0,
							MaxLength:  0,
							MaxItems:   0,
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    0,
					Maximum:    0,
					MinLength:  0,
					MaxLength:  0,
					MaxItems:   0,
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
			wantErr: nil,
		},
		{
			name: "read new item one of property",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "qux",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties: map[string]types.UserConfigSchema{
							"bar": {
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items: &types.UserConfigSchema{
									UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
									Title:                           "",
									Description:                     "",
									Type:                            nil,
									Default:                         nil,
									Properties:                      nil,
									Items:                           nil,
									OneOf: []types.UserConfigSchema{
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "qux",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
										{
											UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
											Title:                           "quux",
											Description:                     "",
											Type:                            nil,
											Default:                         nil,
											Properties:                      nil,
											Items:                           nil,
											OneOf:                           nil,
											Enum:                            nil,
											Minimum:                         0,
											Maximum:                         0,
											MinLength:                       0,
											MaxLength:                       0,
											MaxItems:                        0,
											CreateOnly:                      false,
											Pattern:                         "",
											Example:                         nil,
											UserError:                       "",
										},
									},
									Enum:       nil,
									Minimum:    0,
									Maximum:    0,
									MinLength:  0,
									MaxLength:  0,
									MaxItems:   0,
									CreateOnly: false,
									Pattern:    "",
									Example:    nil,
									UserError:  "",
								},
								OneOf:      nil,
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
						},
						Items:      nil,
						OneOf:      nil,
						Enum:       nil,
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties: map[string]types.UserConfigSchema{
						"bar": {
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
							Title:                           "",
							Description:                     "",
							Type:                            nil,
							Default:                         nil,
							Properties:                      nil,
							Items: &types.UserConfigSchema{
								UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
								Title:                           "",
								Description:                     "",
								Type:                            nil,
								Default:                         nil,
								Properties:                      nil,
								Items:                           nil,
								OneOf: []types.UserConfigSchema{
									{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
										Title:                           "qux",
										Description:                     "",
										Type:                            nil,
										Default:                         nil,
										Properties:                      nil,
										Items:                           nil,
										OneOf:                           nil,
										Enum:                            nil,
										Minimum:                         0,
										Maximum:                         0,
										MinLength:                       0,
										MaxLength:                       0,
										MaxItems:                        0,
										CreateOnly:                      false,
										Pattern:                         "",
										Example:                         nil,
										UserError:                       "",
									},
									{
										UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{
											IsDeprecated:      true,
											DeprecationNotice: "This item is deprecated.",
										},
										Title:       "quux",
										Description: "",
										Type:        nil,
										Default:     nil,
										Properties:  nil,
										Items:       nil,
										OneOf:       nil,
										Enum:        nil,
										Minimum:     0,
										Maximum:     0,
										MinLength:   0,
										MaxLength:   0,
										MaxItems:    0,
										CreateOnly:  false,
										Pattern:     "",
										Example:     nil,
										UserError:   "",
									},
								},
								Enum:       nil,
								Minimum:    0,
								Maximum:    0,
								MinLength:  0,
								MaxLength:  0,
								MaxItems:   0,
								CreateOnly: false,
								Pattern:    "",
								Example:    nil,
								UserError:  "",
							},
							OneOf:      nil,
							Enum:       nil,
							Minimum:    0,
							Maximum:    0,
							MinLength:  0,
							MaxLength:  0,
							MaxItems:   0,
							CreateOnly: false,
							Pattern:    "",
							Example:    nil,
							UserError:  "",
						},
					},
					Items:      nil,
					OneOf:      nil,
					Enum:       nil,
					Minimum:    0,
					Maximum:    0,
					MinLength:  0,
					MaxLength:  0,
					MaxItems:   0,
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
			wantErr: nil,
		},
		{
			name: "gen new enum value",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{Value: "bar"},
							{Value: "baz"},
						},
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{Value: "bar"},
						},
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties:                      nil,
					Items:                           nil,
					OneOf:                           nil,
					Enum: []types.UserConfigSchemaEnumValue{
						{Value: "bar"},
						{Value: "baz"},
					},
					Minimum:    0,
					Maximum:    0,
					MinLength:  0,
					MaxLength:  0,
					MaxItems:   0,
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
			wantErr: nil,
		},
		{
			name: "read new enum value",
			args: args{
				g: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{Value: "bar"},
						},
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
				r: map[string]types.UserConfigSchema{
					"foo": {
						UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
						Title:                           "",
						Description:                     "",
						Type:                            nil,
						Default:                         nil,
						Properties:                      nil,
						Items:                           nil,
						OneOf:                           nil,
						Enum: []types.UserConfigSchemaEnumValue{
							{Value: "bar"},
							{Value: "baz"},
						},
						Minimum:    0,
						Maximum:    0,
						MinLength:  0,
						MaxLength:  0,
						MaxItems:   0,
						CreateOnly: false,
						Pattern:    "",
						Example:    nil,
						UserError:  "",
					},
				},
			},
			want: map[string]types.UserConfigSchema{
				"foo": {
					UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{},
					Title:                           "",
					Description:                     "",
					Type:                            nil,
					Default:                         nil,
					Properties:                      nil,
					Items:                           nil,
					OneOf:                           nil,
					Enum: []types.UserConfigSchemaEnumValue{
						{Value: "bar"},
						{
							UserConfigSchemaDeprecationInfo: types.UserConfigSchemaDeprecationInfo{
								IsDeprecated:      true,
								DeprecationNotice: "This value is deprecated.",
							},
							Value: "baz",
						},
					},
					Minimum:    0,
					Maximum:    0,
					MinLength:  0,
					MaxLength:  0,
					MaxItems:   0,
					CreateOnly: false,
					Pattern:    "",
					Example:    nil,
					UserError:  "",
				},
			},
			wantErr: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := diff(tt.args.g, tt.args.r)
			if !cmp.Equal(err, tt.wantErr) {
				t.Errorf("diff() error = %v, wantErr %v", err, tt.wantErr)
				return
			}

			if !cmp.Equal(got, tt.want) {
				t.Errorf("diff() = %v, want %v", got, tt.want)
			}
		})
	}
}
